//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01_Quiz_Luzin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questios()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int Question_ID { get; set; }
        public int Question_Type { get; set; }
        public string Question_Name { get; set; }
        public string Question_Answer1 { get; set; }
        public string Question_Answer2 { get; set; }
        public string Question_Answer3 { get; set; }
        public string Question_Answer4 { get; set; }
        public string Question_Correct { get; set; }
    
        public virtual Question_type Question_type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
